// eslint-disable-next-line canonical/filename-match-regex
import styled from '@emotion/styled';

export const CSSBaseLine = styled.div(({ theme }) => ({
    '*': {
        boxSizing: 'border-box',
        borderWidth: 0,
        borderStyle: 'solid',
        borderColor: theme.colors.border,
        '::before, ::after': {
            '--tw-border-spacing-x': 0,
            '--tw-border-spacing-y': 0,
            '--tw-translate-x': 0,
            '--tw-translate-y': 0,
            '--tw-rotate': 0,
            '--tw-skew-x': 0,
            '--tw-skew-y': 0,
            '--tw-scale-x': 1,
            '--tw-scale-y': 1,
            '--tw-pan-x': '',
            '--tw-pan-y': '',
            '--tw-pinch-zoom': '',
            '--tw-scroll-snap-strictness': 'proximity',
            '--tw-gradient-from-position': '',
            '--tw-gradient-via-position': '',
            '--tw-gradient-to-position': '',
            '--tw-ordinal': '',
            '--tw-slashed-zero': '',
            '--tw-numeric-figure': '',
            '--tw-numeric-spacing': '',
            '--tw-numeric-fraction': '',
            '--tw-ring-inset': '',
            '--tw-ring-offset-width': '0px',
            '--tw-ring-offset-color': '#fff',
            '--tw-ring-color': 'rgb(59 130 246 / 0.5)',
            '--tw-ring-offset-shadow': '0 0 #0000',
            '--tw-ring-shadow': '0 0 #0000',
            '--tw-shadow': '0 0 #0000',
            '--tw-shadow-colored': '0 0 #0000',
            '--tw-blur': '',
            '--tw-brightness': '',
            '--tw-contrast': '',
            '--tw-grayscale': '',
            '--tw-hue-rotate': '',
            '--tw-invert': '',
            '--tw-saturate': '',
            '--tw-sepia': '',
            '--tw-drop-shadow': '',
            '--tw-backdrop-blur': '',
            '--tw-backdrop-brightness': '',
            '--tw-backdrop-contrast': '',
            '--tw-backdrop-grayscale': '',
            '--tw-backdrop-hue-rotate': '',
            '--tw-backdrop-invert': '',
            '--tw-backdrop-opacity': '',
            '--tw-backdrop-saturate': '',
            '--tw-backdrop-sepia': '',
            '--tw-contain-size': '',
            '--tw-contain-layout': '',
            '--tw-contain-paint': '',
            '--tw-contain-style': '',
        },
    },
    '::backdrop': {
        '--tw-border-spacing-x': '0',
        '--tw-border-spacing-y': '0',
        '--tw-translate-x': '0',
        '--tw-translate-y': '0',
        '--tw-rotate': '0',
        '--tw-skew-x': '0',
        '--tw-skew-y': '0',
        '--tw-scale-x': '1',
        '--tw-scale-y': '1',
        '--tw-pan-x': '',
        '--tw-pan-y': '',
        '--tw-pinch-zoom': '',
        '--tw-scroll-snap-strictness': 'proximity',
        '--tw-gradient-from-position': '',
        '--tw-gradient-via-position': '',
        '--tw-gradient-to-position': '',
        '--tw-ordinal': '',
        '--tw-slashed-zero': '',
        '--tw-numeric-figure': '',
        '--tw-numeric-spacing': '',
        '--tw-numeric-fraction': '',
        '--tw-ring-inset': '',
        '--tw-ring-offset-width': '0px',
        '--tw-ring-offset-color': '#fff',
        '--tw-ring-color': 'rgb(59 130 246 / 0.5)',
        '--tw-ring-offset-shadow': '0 0 #0000',
        '--tw-ring-shadow': '0 0 #0000',
        '--tw-shadow': '0 0 #0000',
        '--tw-shadow-colored': '0 0 #0000',
        '--tw-blur': '',
        '--tw-brightness': '',
        '--tw-contrast': '',
        '--tw-grayscale': '',
        '--tw-hue-rotate': '',
        '--tw-invert': '',
        '--tw-saturate': '',
        '--tw-sepia': '',
        '--tw-drop-shadow': '',
        '--tw-backdrop-blur': '',
        '--tw-backdrop-brightness': '',
        '--tw-backdrop-contrast': '',
        '--tw-backdrop-grayscale': '',
        '--tw-backdrop-hue-rotate': '',
        '--tw-backdrop-invert': '',
        '--tw-backdrop-opacity': '',
        '--tw-backdrop-saturate': '',
        '--tw-backdrop-sepia': '',
        '--tw-contain-size': '',
        '--tw-contain-layout': '',
        '--tw-contain-paint': '',
        '--tw-contain-style': '',
    },
    '::before, ::after': {
        '--tw-content': '""',
    },
    html: {
        lineHeight: 1.5,
        WebkitTextSizeAdjust: '100%',
        MozTabSize: 4,
        OTabSize: 4,
        tabSize: 4,
        fontFamily: `ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"`,
        fontFeatureSettings: 'normal',
        fontVariationSettings: 'normal',
        WebkitTapHighlightColor: 'transparent',
    },
    ':host': {
        lineHeight: 1.5,
        WebkitTextSizeAdjust: '100%',
        MozTabSize: 4,
        OTabSize: 4,
        tabSize: 4,
        fontFamily: `ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"`,
        fontFeatureSettings: 'normal',
        fontVariationSettings: 'normal',
        WebkitTapHighlightColor: 'transparent',
    },
    body: {
        margin: 0,
        lineHeight: 'inherit',
        backgroundColor: theme.colors.background,
        color: theme.colors.foreground,
    },
    hr: {
        height: 0,
        color: 'inherit',
        borderTopWidth: '1px',
    },
    'abbr:where([title])': {
        WebkitTextDecoration: 'underline dotted',
        textDecoration: 'underline dotted',
    },
    'h1, h2, h3, h4, h5, h6': {
        fontSize: 'inherit',
        fontWeight: 'inherit',
    },
    a: {
        color: 'inherit',
        textDecoration: 'inherit',
    },
    'b, strong': {
        fontWeight: 'bolder',
    },
    'code, kbd, samp, pre': {
        fontFamily: `ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace`,
        fontFeatureSettings: 'normal',
        fontVariationSettings: 'normal',
        fontSize: '1em',
    },
    small: {
        fontSize: '80%',
    },
    'sub, sup': {
        fontSize: '75%',
        lineHeight: 0,
        position: 'relative',
        verticalAlign: 'baseline',
    },
    sub: {
        bottom: '-0.25em',
    },
    sup: {
        top: '-0.5em',
    },
    table: {
        textIndent: 0,
        borderColor: 'inherit',
        borderCollapse: 'collapse',
    },
    'button, input, optgroup, select, textarea': {
        fontFamily: 'inherit',
        fontFeatureSettings: 'inherit',
        fontVariationSettings: 'inherit',
        fontSize: '100%',
        fontWeight: 'inherit',
        lineHeight: 'inherit',
        letterSpacing: 'inherit',
        color: 'inherit',
        margin: 0,
        padding: 0,
    },
    'button, select': {
        textTransform: 'none',
    },
    'button, input:where([type="button"]), input:where([type="reset"]), input:where([type="submit"])':
        {
            WebkitAppearance: 'button',
            backgroundColor: 'transparent',
            backgroundImage: 'none',
        },
    ':-moz-focusring': {
        outline: 'auto',
    },
    ':-moz-ui-invalid': {
        boxShadow: 'none',
    },
    progress: {
        verticalAlign: 'baseline',
    },
    '::-webkit-inner-spin-button, ::-webkit-outer-spin-button': {
        height: 'auto',
    },
    '[type="search"]': {
        WebkitAppearance: 'textfield',
        outlineOffset: '-2px',
    },
    '::-webkit-search-decoration': {
        WebkitAppearance: 'none',
    },
    '::-webkit-file-upload-button': {
        WebkitAppearance: 'button',
        font: 'inherit',
    },
    summary: {
        display: 'list-item',
    },
    'blockquote, dl, dd, h1, h2, h3, h4, h5, h6, hr, figure, p, pre': {
        margin: 0,
    },
    fieldset: {
        margin: 0,
        padding: 0,
    },
    legend: {
        padding: 0,
    },
    'ol, ul, menu': {
        listStyle: 'none',
        margin: 0,
        padding: 0,
    },
    dialog: {
        padding: 0,
    },
    textarea: {
        resize: 'vertical',
    },
    'input::-moz-placeholder, textarea::-moz-placeholder': {
        opacity: 1,
        color: '#9ca3af',
    },
    'input::placeholder, textarea::placeholder': {
        opacity: 1,
        color: '#9ca3af',
    },
    'button, [role="button"]': {
        cursor: 'pointer',
    },
    ':disabled': {
        cursor: 'default',
    },
    'img, svg, video, canvas, audio, iframe, embed, object': {
        display: 'block',
        verticalAlign: 'middle',
    },
    'img, video': {
        maxWidth: '100%',
        height: 'auto',
    },
    '[hidden]': {
        display: 'none',
    },
}));
